#! /bin/sh

cat $1 | \
  gawk '{ print gensub(/"([0-9])%"/,                     "0.0\\1",   "g") }' | \
  gawk '{ print gensub(/"([0-9][0-9])%"/,                "0.\\1",    "g") }' | \
  gawk '{ print gensub(/"([0-9][0-9][0-9])%"/,           "1.0",      "g") }' | \
  gawk '{ print gensub(/("N.[A-Za-z]*"):"([0-9.]+)"/,    "\\1:\\2",  "g") }' | \
  gawk '{ print gensub(/("Avg[A-Za-z]*"):"([0-9.]+)"/,   "\\1:\\2",  "g") }' | \
  gawk '{ print gensub(/("AVG.[A-Za-z]*"):"([0-9.]+)"/,  "\\1:\\2",  "g") }' | \
  gawk '{ print gensub(/("Hours"):"([0-9.]+)"/,          "\\1:\\2",  "g") }'
